-- Create the profiles table
CREATE TABLE public.profiles (
    id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    email TEXT UNIQUE,
    full_name TEXT,
    niche TEXT,
    primary_platform TEXT,
    ig_handle TEXT,
    li_handle TEXT,
    x_handle TEXT,
    is_admin BOOLEAN DEFAULT false,
    PRIMARY KEY (id)
);

-- Create the analyses table
CREATE TABLE public.analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    platform TEXT NOT NULL,
    caption TEXT,
    score INTEGER,
    params JSONB,
    flags JSONB,
    fix_guide JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create the keywords table
CREATE TABLE public.keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    term TEXT NOT NULL,
    platform TEXT NOT NULL,
    volume INTEGER,
    trend TEXT,
    difficulty INTEGER,
    set_name TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create the hashtag_sets table
CREATE TABLE public.hashtag_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    name TEXT NOT NULL,
    platform TEXT NOT NULL,
    tags TEXT[],
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create the competitors table
CREATE TABLE public.competitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    name TEXT NOT NULL,
    handle TEXT NOT NULL,
    platform TEXT NOT NULL,
    ig_score INTEGER,
    li_score INTEGER,
    x_score INTEGER,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create the scheduled_posts table
CREATE TABLE public.scheduled_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    platform TEXT NOT NULL,
    caption TEXT,
    seo_score INTEGER,
    scheduled_at TIMESTAMPTZ NOT NULL,
    status TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create the score_history table
CREATE TABLE public.score_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    platform TEXT NOT NULL,
    score INTEGER,
    reach INTEGER,
    recorded_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS for all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hashtag_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.score_history ENABLE ROW LEVEL SECURITY;

-- Policies for user-only access
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can manage their own analyses" ON public.analyses FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own keywords" ON public.keywords FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own hashtag sets" ON public.hashtag_sets FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own competitors" ON public.competitors FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own scheduled posts" ON public.scheduled_posts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own score history" ON public.score_history FOR ALL USING (auth.uid() = user_id);

-- Trigger to create a profile on new user sign-up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
